import {test,expect,type Page} from '@playwright/test';
import {initialPlanInstances} from '../../src/domain/plan-instances';
async function reset(page:Page){
 const old=await (await page.request.get('/api/plan-instances')).json();
 expect((await page.request.post('/api/plan-instances',{data:{revision:old.revision,instances:initialPlanInstances}})).ok()).toBe(true);
 const areas=await (await page.request.get('/api/plan-areas')).json();
 expect((await page.request.post('/api/plan-areas',{data:{revision:areas.revision,areas:{}}})).ok()).toBe(true);
}
test.beforeEach(async({page})=>reset(page));
test.afterEach(async({page})=>reset(page));
test('draw creates an instance; bulk linking, unlinking, deletion and undo persist',async({page})=>{
 await page.goto('/instances');
 const create=page.getByRole('button',{name:'Criar instância',exact:true});await expect(create).toBeEnabled();
 await create.click();await page.getByLabel('Modelo da nova instância').selectOption('CAD-01');
 const svg=page.locator('.instance-drawing svg'),box=(await svg.boundingBox())!;
 await page.mouse.move(box.x+box.width*100/882,box.y+box.height*155/580);await page.mouse.down();
 await page.mouse.move(box.x+box.width*124/882,box.y+box.height*175/580,{steps:5});await page.mouse.up();
 const newItem=page.locator('g[data-instance-id^="instance-"]');await expect(newItem).toHaveCount(1);
 const id=await newItem.getAttribute('data-instance-id');
 await page.keyboard.press('Escape');
 await page.getByLabel('Modelo da seleção').selectOption('CAD-03');
 await expect(newItem).toHaveAttribute('data-model-id','CAD-03');
 const original=page.locator('g[data-instance-id="chair-cad-01-001"]');
 await original.focus();await page.keyboard.press('Space');
 await page.getByLabel('Modelo da seleção').selectOption('CAD-02');
 await expect(original).toHaveAttribute('data-model-id','CAD-02');await expect(newItem).toHaveAttribute('data-model-id','CAD-02');
 await page.getByRole('button',{name:'Desvincular',exact:true}).click();
 await expect(newItem).toHaveAttribute('data-model-id','');
 await page.getByRole('button',{name:'Remover da planta',exact:true}).click();await expect(newItem).toHaveCount(0);await expect(original).toHaveCount(0);
 await page.getByRole('button',{name:'Desfazer',exact:true}).click();await expect(newItem).toHaveCount(1);await expect(original).toHaveCount(1);
 await page.route('**/api/plan-instances',route=>route.request().method()==='POST'?route.fulfill({status:503,json:{error:'Falha de teste. Tente novamente.'}}):route.continue());
 await page.getByRole('button',{name:'Salvar instâncias',exact:true}).click();await expect(page.locator('.instance-error')).toContainText('Falha de teste');
 await page.unroute('**/api/plan-instances');
 await page.getByRole('button',{name:'Salvar instâncias',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Instâncias salvas no projeto.');
 await page.reload();await expect(page.locator('g[data-instance-id="'+id+'"]')).toHaveAttribute('data-model-id','');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/instances-simple-mobile.png',fullPage:true});
});
test('move, resize and save update both editor and project plan',async({page})=>{
 await page.goto('/instances');
 const item=page.locator('g[data-instance-id="chair-cad-01-001"]');await expect(item).toHaveAttribute('aria-disabled','false');
 const rect=item.locator('rect'),x=Number(await rect.getAttribute('x')),w=Number(await rect.getAttribute('width'));
 const svg=page.locator('.instance-drawing svg'),scale=(await svg.boundingBox())!.width/882,b=(await rect.boundingBox())!;
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+5*scale,b.y+b.height/2+4*scale,{steps:5});await page.mouse.up();
 expect(Number(await rect.getAttribute('x'))).toBeCloseTo(x+5,0);
 const h=(await page.locator('[data-handle="se"]').boundingBox())!;
 await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x+h.width/2+6*scale,h.y+h.height/2+5*scale,{steps:5});await page.mouse.up();
 expect(Number(await rect.getAttribute('width'))).toBeCloseTo(w+6,0);
 await page.getByRole('button',{name:'Salvar instâncias',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Instâncias salvas no projeto.');
 await page.reload();await expect(item).toBeVisible();expect(Number(await rect.getAttribute('width'))).toBeCloseTo(w+6,0);
 await page.goto('/');await page.getByRole('button',{name:'Planta do projeto',exact:true}).click();
 await page.getByLabel('Ambiente da planta').selectOption('PRISMAL_WORK_WEST');
 const target=page.locator('[data-element-id="chair-cad-01-001"] rect');
 await expect(target).toBeVisible();expect(Number(await target.getAttribute('width'))).toBeCloseTo(w+6,2);
});
test('area editing refines vertices and repeated room activation reverses focus',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Planta do projeto',exact:true}).click();
 const dialog=page.locator('dialog.astra-dialog[open]');
 await expect(dialog.getByLabel('Ambiente da planta').locator('option')).toHaveCount(15);
 await expect(dialog.getByRole('button',{name:'Open Elevador 01',exact:true})).toHaveCount(0);
 await dialog.getByLabel('Ambiente da planta').selectOption('PRISMAL_WORK_WEST');
 await expect(dialog.locator('.plan-focus-scene')).toHaveCSS('transform',/matrix\(1.14/);
 await dialog.getByRole('button',{name:'Open Estações de trabalho',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(dialog.getByLabel('Ambiente da planta')).toHaveValue('');
 await expect(dialog.locator('.plan-focus-scene')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 await expect(dialog.locator('.plan-focus-background')).toHaveCSS('opacity','0');
 const roomButton=dialog.getByRole('button',{name:'01 Estações de trabalho',exact:true});
 await roomButton.click();await expect(dialog.getByLabel('Ambiente da planta')).toHaveValue('PRISMAL_WORK_WEST');
 await roomButton.click();await expect(dialog.getByLabel('Ambiente da planta')).toHaveValue('');
 await dialog.getByRole('button',{name:'Editar áreas',exact:true}).click();
 const editor=dialog.getByRole('region',{name:'Editar áreas da planta'});
 await editor.getByLabel('Área em edição').selectOption('PRISMAL_WORK_WEST');
 const vertex=editor.getByRole('button',{name:'Ponto 1',exact:true});
 const x=Number(await vertex.getAttribute('cx'));await vertex.focus();await page.keyboard.press('ArrowRight');
 expect(Number(await vertex.getAttribute('cx'))).toBeCloseTo(x+1,3);
 await editor.getByRole('button',{name:'Adicionar ponto após 1',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(editor.locator('.plan-area-vertex')).toHaveCount(5);
 await editor.getByRole('button',{name:'Remover ponto',exact:true}).click();await expect(editor.locator('.plan-area-vertex')).toHaveCount(4);
 await page.screenshot({path:'test-results/area-refinement.png'});
 await editor.getByRole('button',{name:'Salvar áreas',exact:true}).click();await expect(editor).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:'Planta do projeto',exact:true}).click();
 await page.getByRole('button',{name:'Editar áreas',exact:true}).click();
 await page.getByLabel('Área em edição').selectOption('PRISMAL_WORK_WEST');
 expect(Number(await page.getByRole('button',{name:'Ponto 1',exact:true}).getAttribute('cx'))).toBeCloseTo(x+1,3);
 await page.getByRole('button',{name:'Ponto 1',exact:true}).focus();await page.keyboard.press('ArrowRight');
 await page.getByRole('button',{name:'Cancelar edição',exact:true}).click();
 await page.getByRole('button',{name:'Editar áreas',exact:true}).click();
 expect(Number(await page.getByRole('button',{name:'Ponto 1',exact:true}).getAttribute('cx'))).toBeCloseTo(x+1,3);
});
